# Generated by Django 2.1.3 on 2019-03-27 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cert_type_code_zz',
            fields=[
                ('cert_type_code_xx', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('code_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='certificategenerator_y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=1)),
                ('subsidiary_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('year_code', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(100)])),
                ('pv_type_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('cert_type_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.cert_type_code_zz')),
            ],
        ),
        migrations.CreateModel(
            name='certificatez',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('cert_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.certificategenerator_y')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('idd_client', models.IntegerField(default=1)),
                ('client_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(1)])),
                ('client_nam', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('client_type', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=42)),
                ('lastname', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=42)),
                ('contribution_type', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='expertise',
            fields=[
                ('id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('certification', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='factory_inspection_jj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_xx', models.IntegerField(default=1)),
                ('locatio_id', models.CharField(max_length=42)),
                ('type_of_inspection', models.CharField(blank=True, max_length=2)),
                ('pvv_type', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('date', models.CharField(blank=True, max_length=42)),
                ('inspector', models.CharField(blank=True, max_length=42)),
                ('inspection_sequence', models.CharField(blank=True, max_length=42)),
                ('findings', models.CharField(blank=True, max_length=42)),
                ('cert_no_ab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.certificatez')),
            ],
        ),
        migrations.CreateModel(
            name='file_generator_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq2', models.IntegerField(default=1000)),
                ('reggion_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('yearr_codde', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(10)])),
                ('pv_type_code', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
                ('typpe_numbb', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.IntegerField(default=100000, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)])),
                ('name', models.CharField(blank=True, max_length=42)),
                ('address1', models.CharField(blank=True, max_length=42)),
                ('address2', models.CharField(blank=True, max_length=42)),
                ('city', models.CharField(blank=True, max_length=42)),
                ('state', models.CharField(blank=True, max_length=42)),
                ('zip', models.CharField(blank=True, max_length=42)),
                ('country', models.CharField(blank=True, max_length=42)),
                ('phone', models.CharField(blank=True, max_length=42)),
                ('fax', models.CharField(blank=True, max_length=42)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.client')),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('performance_id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('max_system_voltage', models.CharField(blank=True, max_length=42)),
                ('name', models.CharField(blank=True, max_length=42)),
                ('open_circuit_voltage', models.CharField(blank=True, max_length=42)),
                ('short_circuit_current', models.CharField(blank=True, max_length=42)),
                ('voltage_at_max_power', models.CharField(blank=True, max_length=42)),
                ('current_at_max_power', models.CharField(blank=True, max_length=42)),
                ('max_power_output', models.CharField(blank=True, max_length=42)),
                ('fill_factor', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('prod_id', models.IntegerField(default=1)),
                ('model_no', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=42)),
                ('type', models.CharField(blank=True, max_length=42)),
                ('fireclass', models.CharField(blank=True, max_length=42)),
                ('length', models.CharField(blank=True, max_length=42)),
                ('weight', models.CharField(blank=True, max_length=42)),
                ('individual_cell_area', models.CharField(blank=True, max_length=42)),
                ('cell_technology', models.CharField(blank=True, max_length=42)),
                ('cell_manufacturer', models.CharField(blank=True, max_length=42)),
                ('cell_part_no', models.CharField(blank=True, max_length=42)),
                ('cell_manufacturer_location', models.CharField(blank=True, max_length=42)),
                ('total_number_of_cells', models.CharField(blank=True, max_length=42)),
                ('no_of_cells_in_series', models.CharField(blank=True, max_length=42)),
                ('number_of_series_strings', models.CharField(blank=True, max_length=42)),
                ('number_of_bypass_diodes', models.CharField(blank=True, max_length=42)),
                ('bypass_diode_rating', models.CharField(blank=True, max_length=42)),
                ('bypass_diode_max_temp', models.CharField(blank=True, max_length=42)),
                ('series_fuse_rating', models.CharField(blank=True, max_length=42)),
                ('interconnect_material_and_material_contact_number', models.CharField(blank=True, max_length=42)),
                ('interconnect_dimensions', models.CharField(blank=True, max_length=42)),
                ('superstrate_type', models.CharField(blank=True, max_length=42)),
                ('supersrtate_manufacturer_and_part_no', models.CharField(blank=True, max_length=42)),
                ('substrate_type', models.CharField(blank=True, max_length=42)),
                ('subsrtate_manufacturer_and_part_no', models.CharField(blank=True, max_length=42)),
                ('frame_type_or_material', models.CharField(blank=True, max_length=42)),
                ('frame_adhesive', models.CharField(blank=True, max_length=42)),
                ('encapsulant_type', models.CharField(blank=True, max_length=42)),
                ('encapsulant_manufacturer_and_part_no', models.CharField(blank=True, max_length=42)),
                ('junction_box_type', models.CharField(blank=True, max_length=42)),
                ('junction_box_manufacturer_and_part_no', models.CharField(blank=True, max_length=42)),
                ('junction_box_potting_material', models.CharField(blank=True, max_length=42)),
                ('junction_box_adhesive', models.CharField(blank=True, max_length=42)),
                ('junction_box_use_with_contuit', models.CharField(blank=True, max_length=42)),
                ('cable_connector_type', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='product_certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_numb', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)])),
                ('certific_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.certificategenerator_y')),
                ('location_idd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.location')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_u', models.IntegerField(default=1)),
                ('contact', models.CharField(blank=True, max_length=42)),
                ('loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.location')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.product')),
            ],
        ),
        migrations.CreateModel(
            name='report_no2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_nummber', models.CharField(blank=True, max_length=42)),
                ('page_numberr', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('sequence_id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_name', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('service_description', models.CharField(blank=True, max_length=42)),
                ('fi_required', models.CharField(blank=True, max_length=42)),
                ('fi_frequency', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='temp2',
            fields=[
                ('idd', models.CharField(max_length=42, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tempp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=42)),
                ('y', models.CharField(max_length=42)),
                ('z', models.CharField(max_length=42)),
                ('m', models.IntegerField(default=170)),
            ],
        ),
        migrations.CreateModel(
            name='test_standard',
            fields=[
                ('test_name', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('test_description', models.CharField(blank=True, max_length=42)),
                ('publish_date', models.CharField(blank=True, max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('first_name', models.CharField(max_length=42)),
                ('middle_name', models.CharField(blank=True, max_length=42)),
                ('last_name', models.CharField(max_length=42)),
                ('job_title', models.CharField(blank=True, max_length=42)),
                ('email', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('office_phone', models.CharField(blank=True, max_length=42)),
                ('cell_phone', models.CharField(blank=True, max_length=42)),
                ('password', models.CharField(blank=True, max_length=42)),
                ('prefix', models.CharField(blank=True, max_length=42)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tempp',
            unique_together={('x', 'y', 'z', 'm')},
        ),
        migrations.AddField(
            model_name='temp2',
            name='gg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.tempp'),
        ),
        migrations.AddField(
            model_name='service',
            name='test_standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.test_standard'),
        ),
        migrations.AlterUniqueTogether(
            name='report_no2',
            unique_together={('report_nummber', 'page_numberr')},
        ),
        migrations.AddField(
            model_name='performance',
            name='model_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.product'),
        ),
        migrations.AddField(
            model_name='performance',
            name='sequenc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.sequence'),
        ),
        migrations.AlterUniqueTogether(
            name='file_generator_number',
            unique_together={('reggion_code', 'yearr_codde', 'typpe_numbb', 'pv_type_code', 'seq2')},
        ),
        migrations.AddField(
            model_name='expertise',
            name='test_sttd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.test_standard'),
        ),
        migrations.AddField(
            model_name='certificatez',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.client'),
        ),
        migrations.AddField(
            model_name='certificatez',
            name='contact_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.user'),
        ),
        migrations.AddField(
            model_name='certificatez',
            name='test_std',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certifi.test_standard'),
        ),
        migrations.AlterUniqueTogether(
            name='product_certificate',
            unique_together={('certific_no', 'prod', 'location_idd', 'page_numb')},
        ),
        migrations.AlterUniqueTogether(
            name='factory_inspection_jj',
            unique_together={('type_of_inspection', 'pvv_type', 'locatio_id')},
        ),
        migrations.AlterUniqueTogether(
            name='certificategenerator_y',
            unique_together={('subsidiary_code', 'year_code', 'pv_type_code', 'seq')},
        ),
    ]
