# Generated by Django 2.1.3 on 2019-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifi', '0004_auto_20190328_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
