# Generated by Django 2.1.3 on 2019-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifi', '0005_auto_20190329_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='max_system_voltage',
        ),
        migrations.AddField(
            model_name='product',
            name='max_system_voltage',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
